[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "violet-agents"
version = "0.1.0"
description = "简单的agent框架"
requires-python = ">=3.1.0"
dependencies = [
    "openai>=2.37.0",
    "python-dotenv>=0.19.0",
    "fastmcp>=3.3.1",
    "numpy>=2.2.6",
    "scikit-learn>=1.7.2",
]
readme = "README.md"
license = {text = "MIT"}
authors = [
    { name = "ByteKnight", email = "esqaNN@163.com" }
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pylint>=4.0.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]